using CRM.Base.Common;

namespace CRM.Data.Seeds;

/// <summary>
/// Seeds the Operations → Processing reference data from the "BATCH PRODUCTION SCHEDULING" workbook
/// (staging JSON produced by <c>tools/import/extract_processing.py</c>): the Packaging Store location,
/// the three Processing categories, one Inventory item per stock-card material / produce, and the
/// product master. No historical rows — the workbook remains the record of those.
///
/// Materials the extractor matched to an item from the earlier inventory import (<c>reuseSku</c>) are
/// moved into their Processing category rather than duplicated, keeping their stock. Everything else
/// starts at zero on hand. Every created/inferred value is listed in docs/IMPORT-NOTES.md.
///
/// Idempotent: a material already present in a Processing category (by case/space-insensitive name)
/// and a product already present by name are left alone.
/// </summary>
public class ProcessingDataSeeder
{
    private const string MainStore = "Main Store";
    private const string PackagingStore = "Packaging Store";
    private const string SkuPrefix = "PROC-";

    private readonly ApplicationDbContext _context;

    public ProcessingDataSeeder(ApplicationDbContext context)
    {
        _context = context;
    }

    public async Task<string> InitializeAsync()
    {
        // The SYSTEM tenant's id is generated by the database; never fall back to Guid.Empty, which
        // would file everything under a tenant that does not exist.
        var tenant = await _context.Tenants.IgnoreQueryFilters().FirstOrDefaultAsync(t => t.Code == "SYSTEM");
        if (tenant == null)
            return "Processing data skipped: no SYSTEM tenant.";
        var tenantId = tenant.Id;

        var locationByName = await SeedLocationsAsync(tenantId);
        var categoryByName = await SeedCategoriesAsync(tenantId);
        var (created, reused) = await SeedMaterialsAsync(tenantId, categoryByName, locationByName);
        var products = await SeedProductsAsync(tenantId);

        return $"Processing seeded: {created} materials created, {reused} reused from inventory, {products} products.";
    }

    private async Task<Dictionary<string, Guid>> SeedLocationsAsync(Guid tenantId)
    {
        var existing = await _context.Locations.IgnoreQueryFilters()
            .Where(l => l.TenantId == tenantId && !l.IsDeleted)
            .Select(l => l.Name).ToListAsync();

        foreach (var (name, type) in new[] { (MainStore, LocationType.Warehouse), (PackagingStore, LocationType.PackingArea) })
        {
            if (existing.Contains(name)) continue;
            _context.Locations.Add(new Location
            {
                Id = Guid.NewGuid(),
                Code = RandomGenerator.RandomString(10),
                Name = name,
                Type = type,
                TenantId = tenantId,
            });
        }
        await _context.SaveChangesAsync();

        return (await _context.Locations.IgnoreQueryFilters()
                .Where(l => l.TenantId == tenantId && !l.IsDeleted).ToListAsync())
            .GroupBy(l => l.Name).ToDictionary(g => g.Key, g => g.First().Id);
    }

    private async Task<Dictionary<string, Guid>> SeedCategoriesAsync(Guid tenantId)
    {
        var existing = await _context.Categories.IgnoreQueryFilters()
            .Where(c => c.TenantId == tenantId && !c.IsDeleted)
            .Select(c => c.Name).ToListAsync();

        foreach (var name in ProcessingCategories.All.Where(n => !existing.Contains(n)))
        {
            _context.Categories.Add(new Category
            {
                Id = Guid.NewGuid(),
                Code = RandomGenerator.RandomString(10),
                Name = name,
                Description = "Batch Production Scheduling workbook stock cards (Operations → Processing).",
                TenantId = tenantId,
            });
        }
        await _context.SaveChangesAsync();

        return (await _context.Categories.IgnoreQueryFilters()
                .Where(c => c.TenantId == tenantId && !c.IsDeleted && ProcessingCategories.All.Contains(c.Name))
                .ToListAsync())
            .GroupBy(c => c.Name).ToDictionary(g => g.Key, g => g.First().Id);
    }

    private async Task<(int Created, int Reused)> SeedMaterialsAsync(
        Guid tenantId, Dictionary<string, Guid> categoryByName, Dictionary<string, Guid> locationByName)
    {
        var items = await _context.Items.IgnoreQueryFilters()
            .Where(i => i.TenantId == tenantId && !i.IsDeleted)
            .ToListAsync();

        var processingCategoryIds = categoryByName.Values.ToHashSet();
        var alreadyProcessing = items
            .Where(i => i.CategoryId.HasValue && processingCategoryIds.Contains(i.CategoryId.Value))
            .Select(i => Normalize(i.Name))
            .ToHashSet();
        var bySku = items.GroupBy(i => i.Sku).ToDictionary(g => g.Key, g => g.First());
        var nextSku = items
            .Where(i => i.Sku.StartsWith(SkuPrefix))
            .Select(i => int.TryParse(i.Sku[SkuPrefix.Length..], out var n) ? n : 0)
            .DefaultIfEmpty(0).Max() + 1;

        int created = 0, reused = 0;
        foreach (var m in EupepsiaSeedData.ProcessingMaterials())
        {
            if (!alreadyProcessing.Add(Normalize(m.Name)))
                continue;

            var categoryId = categoryByName[m.CategoryName];
            var locationId = locationByName.TryGetValue(m.LocationName, out var lid) ? lid : (Guid?)null;

            if (m.ReuseSku != null && bySku.TryGetValue(m.ReuseSku, out var existing))
            {
                existing.CategoryId = categoryId;
                existing.LocationId ??= locationId;
                reused++;
                continue;
            }

            var sku = $"{SkuPrefix}{nextSku++:0000}";
            _context.Items.Add(new Item
            {
                Id = Guid.NewGuid(),
                Code = sku,
                Sku = sku,
                Name = m.Name,
                CategoryId = categoryId,
                LocationId = locationId,
                UnitType = string.IsNullOrWhiteSpace(m.UnitType) ? "piece" : m.UnitType,
                QuantityOnHand = 0,
                TenantId = tenantId,
            });
            created++;
        }

        await _context.SaveChangesAsync();
        return (created, reused);
    }

    private async Task<int> SeedProductsAsync(Guid tenantId)
    {
        var existing = (await _context.ProcessingProducts.IgnoreQueryFilters()
                .Where(p => p.TenantId == tenantId && !p.IsDeleted)
                .Select(p => p.Name).ToListAsync())
            .Select(Normalize).ToHashSet();

        var added = 0;
        foreach (var p in EupepsiaSeedData.ProcessingProducts())
        {
            if (!existing.Add(Normalize(p.Name))) continue;
            _context.ProcessingProducts.Add(new ProcessingProduct
            {
                Id = Guid.NewGuid(),
                Code = RandomGenerator.RandomString(10),
                Name = p.Name,
                ProductCode = p.ProductCode,
                Upc = p.Upc,
                Sku = p.Sku,
                RawMaterialId = p.RawMaterialId,
                ProcessingDuration = p.ProcessingDuration,
                TenantId = tenantId,
            });
            added++;
        }
        await _context.SaveChangesAsync();
        return added;
    }

    private static string Normalize(string name) => string.Join(' ', name.Split(' ', StringSplitOptions.RemoveEmptyEntries)).ToUpperInvariant();
}
