using AutoMapper;
using CRM.Base.Common.Domain.Entities;
using CRM.Base.Repositories.Implementations;
using CRM.Data;
using CRM.Domain.Entities;
using CRM.Tests.Helpers;
using FluentAssertions;
using Microsoft.AspNetCore.Http;
using Moq;
using Xunit;

namespace CRM.Tests.Services;

/// <summary>
/// Regression cover for the sidebar feed.
///
/// The seed data puts the ADMIN role in tenant <see cref="Guid.Empty"/> (RoleSeedData) while real
/// users are provisioned into the SYSTEM tenant, whose Id is generated by the database. Since
/// <see cref="Role"/> is tenant-scoped, that mismatch could plausibly cause EF's global query
/// filter to drop <c>ur.Role</c> and break <c>GetMyMenusAsync</c>. It does not — this test pins
/// that behaviour down so a future change to the filters or the seed cannot silently empty
/// everyone's sidebar.
/// </summary>
public class MenuServiceMyMenusTests
{
    private readonly Guid _tenantId = Guid.NewGuid();   // the "real" SYSTEM tenant id
    private const string Oid = "entra-oid-1";

    private static MenuService BuildService(ApplicationDbContext db) => new(
        new MSSQLRepository<Menu, Guid>(db),
        new MSSQLRepository<User, Guid>(db),
        new MSSQLRepository<Permission, Guid>(db),
        new MSSQLRepository<TenantModule, Guid>(db),
        new MSSQLRepository<MenuPermission, Guid>(db),
        new MSSQLRepository<AuditLog, long>(db),
        db,
        new Mock<IMapper>().Object,
        new Mock<IHttpContextAccessor>().Object);

    /// <summary>Arranges a user whose ADMIN role lives in the global (Guid.Empty) tenant.</summary>
    private ApplicationDbContext Arrange(SqliteTestDb sqlite)
    {
        var db = sqlite.Context;

        var userId = Guid.NewGuid();
        var adminRoleId = Guid.NewGuid();

        db.Set<User>().Add(new User
        {
            Id = userId,
            Email = "admin@example.com",
            EntraObjectId = Oid,
            TenantId = _tenantId,
            IsActive = true,
        });

        // Exactly what RoleSeedData does: the ADMIN role is global, not tenant-scoped.
        db.Set<Role>().Add(new Role
        {
            Id = adminRoleId,
            Name = "Administrator",
            Code = "ADMIN",
            IsActive = true,
            TenantId = Guid.Empty,
        });

        db.Set<UserRole>().Add(new UserRole
        {
            Id = Guid.NewGuid(),
            UserId = userId,
            RoleId = adminRoleId,
            TenantId = _tenantId,
        });

        // The tenant has the CORE module switched on, so CORE menus are in scope.
        // CORE comes from the static HasData seed that EnsureCreated applies.
        var coreModule = db.Set<Module>().Single(m => m.Code == "CORE");
        db.Set<TenantModule>().Add(new TenantModule
        {
            Id = Guid.NewGuid(),
            TenantId = _tenantId,
            ModuleId = coreModule.Id,
            IsActive = true,
        });

        db.SaveChanges();
        db.ChangeTracker.Clear();
        return db;
    }

    [Fact]
    public async Task GetMyMenusAsync_returns_menus_for_an_admin_whose_role_is_global()
    {
        using var sqlite = SqliteTestDb.Create(_tenantId);
        var db = Arrange(sqlite);
        var service = BuildService(db);

        var result = await service.GetMyMenusAsync(Oid, _tenantId);

        result.IsSuccess.Should().BeTrue(
            "an administrator must receive their sidebar; instead: {0}", result.ErrorMessage);
        result.Content.Should().NotBeEmpty("the CORE module is active, so CORE menus are in scope");
    }
}
